### ISSUE TITLE
Support connecting to multiple vCenters?

### ISSUE THREAD

**Issue by chriscarpenter12** [openshift/vmware-vsphere-csi-driver-operator#89]
Does the CSI driver support multiple vCenter connections? It looks like the [config](https://github.com/openshift/vmware-vsphere-csi-driver-operator/blob/master/assets/vsphere_cloud_config.yaml) has a generic `cloud.conf` defined. Whenever this config map is modified it's overridden with the interpolated values.

We're running on a stretch cluster and during a test cluster upgrade it's only connecting to one of our vCenters so far and can't find the VM UUID of other nodes in other vmware clusters.

**Comment by gnufied** [comment]
In tree vsphere cloudprovider deprecated support for multiple vcenters long back - https://github.com/kubernetes/kubernetes/pull/98546 and vsphere CSI driver does not support multiple vcenters as well - https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/docs/book/features/vsphere_csi_migration.md

Those are the reasons, this operator does not support multiple vcenters.
